# Generated by Django 5.2.6 on 2025-09-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="currency",
            field=models.CharField(default="INR", max_length=3),
        ),
    ]
