# Generated by Django 5.2.6 on 2025-09-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notificationpreference",
            name="push_enabled",
        ),
        migrations.RemoveField(
            model_name="notificationpreference",
            name="sms_enabled",
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="channel",
            field=models.CharField(
                choices=[("telegram", "Telegram"), ("email", "Email")], max_length=20
            ),
        ),
    ]
